import { EmailContextProvider } from '@/app/stages/email/email.context'
import { ApplianceContextProvider } from '@/app/stages/appliances/appliance.context';
import { EnergyContextProvider } from '@/app/stages/energytotal/energy.context';

import type { Metadata } from "next";
import "./globals.css";

import { montserrat } from './ui/fonts';

export const metadata: Metadata = {
  title: "Tilt Exercise - Nicolas Robinson",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <EmailContextProvider>
          <ApplianceContextProvider>
            <EnergyContextProvider>{children}</EnergyContextProvider>
          </ApplianceContextProvider>
        </EmailContextProvider>
      </body>
    </html>
  );
}
