import { EmailContextProvider } from '@/app/step-1/email.context'
import { ApplianceContextProvider } from '@/app/step-2/appliance.context';
import { EnergyContextProvider } from '@/app/step-3/energy.context';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EmailContextProvider>
          <ApplianceContextProvider>
            <EnergyContextProvider>{children}</EnergyContextProvider>
          </ApplianceContextProvider>
        </EmailContextProvider>
      </body>
    </html>
  );
}
